# Generated by Django 4.1.5 on 2023-01-20 03:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sector', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Top500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('date', models.DateField(unique=True)),
                ('month1', models.FloatField(blank=True, null=True)),
                ('month2', models.FloatField(blank=True, null=True)),
                ('month3', models.FloatField(blank=True, null=True)),
                ('month4', models.FloatField(blank=True, null=True)),
                ('month6', models.FloatField(blank=True, null=True)),
                ('year1', models.FloatField(blank=True, null=True)),
                ('year2', models.FloatField(blank=True, null=True)),
                ('year3', models.FloatField(blank=True, null=True)),
                ('year5', models.FloatField(blank=True, null=True)),
                ('year7', models.FloatField(blank=True, null=True)),
                ('year10', models.FloatField(blank=True, null=True)),
                ('year20', models.FloatField(blank=True, null=True)),
                ('year30', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YahooStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.company')),
            ],
            options={
                'ordering': ['-date', 'company'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YahooAssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.asset')),
            ],
            options={
                'ordering': ['-date', 'asset'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='treasuryrates',
            index=models.Index(fields=['date'], name='markets_tre_date_4a8610_idx'),
        ),
        migrations.AddField(
            model_name='top500',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top500', to='markets.company'),
        ),
        migrations.AddField(
            model_name='share',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.company'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['code'], name='markets_com_code_bc2489_idx'),
        ),
        migrations.AddConstraint(
            model_name='yahoostockprice',
            constraint=models.UniqueConstraint(fields=('date', 'company'), name='markets_yahoostockprice_date_company'),
        ),
        migrations.AddConstraint(
            model_name='yahooassetprice',
            constraint=models.UniqueConstraint(fields=('date', 'asset'), name='markets_yahooassetprice_date_asset'),
        ),
        migrations.AddConstraint(
            model_name='top500',
            constraint=models.UniqueConstraint(fields=('date', 'company'), name='markets_top500_date_company'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['date'], name='markets_sha_date_7c635b_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['count'], name='markets_sha_count_7ad487_idx'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('company', 'date'), name='markets_share_date_company'),
        ),
    ]
